version: '3.1'

services:
  web:
    container_name: web
    image: frontend:latest
    restart: always
    ports:
      - 8000:80
    depends_on:
      - backend_db
  
  backend_db:
    image: backend:latest
    restart: always
  
  sample:
    build: ./frontend
    container_name: sample
    restart: always
    ports:
      - 9000:80
    depends_on:
      - backend_db