version: '3.1'

services:
  web:
    build: ./frontend
    container_name: web
    image: frontend:latest
    restart: always
    ports:
      - 8000:80
    depends_on:
      - backend_db
  
  backend_db:
    build: ./backend
    container_name: database
    restart: always
  